const CATEGORIES = [
  { id: 'basics',      name: '基础概念',   icon: '🧱', color: '#4A90D9' },
  { id: 'llm',         name: '大模型相关', icon: '🧠', color: '#7B68EE' },
  { id: 'training',    name: '训练与调优', icon: '⚙️',  color: '#E67E22' },
  { id: 'application', name: '应用与交互', icon: '💬', color: '#27AE60' },
  { id: 'evaluation',  name: '评估与能力', icon: '📊', color: '#E74C3C' },
  { id: 'product',     name: '产品落地',   icon: '🚀', color: '#16A085' },
];

const TERMS = [
  // ── 第1类：基础概念（按使用频率由高到低）──────────────────────
  { en:'Artificial Intelligence', zh:'人工智能', cat:'basics',
    def:'让机器模拟人类思考和决策能力的技术总称。',
    analogy:'就像给机器装了一个"会思考的大脑"。' },
  { en:'Machine Learning', zh:'机器学习', cat:'basics',
    def:'机器通过大量数据自动找规律、自我改进，无需逐条编程。',
    analogy:'就像小孩看了1000张猫的照片后，自己学会认猫。' },
  { en:'Model', zh:'模型', cat:'basics',
    def:'经过训练后能对新数据做出预测或判断的程序。',
    analogy:'就像经过大量练习后形成的"解题套路"。' },
  { en:'Deep Learning', zh:'深度学习', cat:'basics',
    def:'用多层神经网络处理复杂数据，是机器学习的高级形式。',
    analogy:'就像大脑皮层有很多层，每层负责处理不同细节。' },
  { en:'Dataset', zh:'数据集', cat:'basics',
    def:'用于训练或测试模型的一批有组织的数据。',
    analogy:'就像学生练习用的一本习题册。' },
  { en:'Training', zh:'训练', cat:'basics',
    def:'让模型反复学习数据、调整参数直到表现良好的过程。',
    analogy:'就像运动员每天练习，不断提升成绩。' },
  { en:'Inference', zh:'推理/推断', cat:'basics',
    def:'用训练好的模型对新输入做出预测的过程。',
    analogy:'就像学完数学后，用学到的方法解新题。' },
  { en:'Neural Network', zh:'神经网络', cat:'basics',
    def:'模仿人脑神经元连接方式构建的计算模型。',
    analogy:'就像一张由无数节点和连线组成的渔网。' },
  { en:'Algorithm', zh:'算法', cat:'basics',
    def:'解决特定问题的一套明确步骤和规则。',
    analogy:'就像菜谱，按步骤操作就能做出特定的菜。' },
  { en:'Accuracy', zh:'准确率', cat:'basics',
    def:'模型预测正确的样本占总样本的比例。',
    analogy:'就像考试答对题目数除以总题目数。' },
  { en:'Prediction', zh:'预测', cat:'basics',
    def:'模型根据输入数据给出的输出结果。',
    analogy:'就像医生根据症状给出的诊断结论。' },
  { en:'Parameter', zh:'参数', cat:'basics',
    def:'模型内部的可调数值，决定模型的行为和输出。',
    analogy:'就像收音机上的旋钮，调整它改变声音效果。' },
  { en:'Supervised Learning', zh:'监督学习', cat:'basics',
    def:'用带标签的数据训练模型，让它学会从输入预测输出。',
    analogy:'就像老师带着答案教学生做题。' },
  { en:'Label', zh:'标签', cat:'basics',
    def:'训练数据中人工标注的正确答案。',
    analogy:'就像老师在作业本上写的"正确答案"。' },
  { en:'Feature', zh:'特征', cat:'basics',
    def:'输入数据中对预测有用的属性或维度。',
    analogy:'就像相亲时关注的"身高、学历、收入"等关键信息。' },
  { en:'Overfitting', zh:'过拟合', cat:'basics',
    def:'模型在训练数据上表现极好，但遇到新数据就失灵。',
    analogy:'就像只会背答案，换道题就不会了。' },
  { en:'Annotation', zh:'数据标注', cat:'basics',
    def:'人工为原始数据添加标签或说明，供模型学习。',
    analogy:'就像给照片手动写上"这是猫""这是狗"的说明。' },
  { en:'Embedding', zh:'嵌入/向量化', cat:'basics',
    def:'将文字、图片等信息转换为数字向量的表示方法。',
    analogy:'就像把每个词翻译成一串坐标，意思相近的词坐标也相近。' },
  { en:'Classification', zh:'分类', cat:'basics',
    def:'将输入数据判断归属于哪个预定类别的任务。',
    analogy:'就像邮局按地址把信件分到不同的格子里。' },
  { en:'Generalization', zh:'泛化能力', cat:'basics',
    def:'模型在未见过的新数据上保持良好表现的能力。',
    analogy:'就像真正学懂了数学，能举一反三解新题。' },
  { en:'Loss Function', zh:'损失函数', cat:'basics',
    def:'衡量模型预测结果与真实答案差距的计算公式。',
    analogy:'就像考试的扣分规则，差得越多扣分越多。' },
  { en:'Reinforcement Learning', zh:'强化学习', cat:'basics',
    def:'通过奖惩机制让模型在试错中学习最优策略。',
    analogy:'就像训练小狗，做对了给零食，做错了不给。' },
  { en:'Unsupervised Learning', zh:'无监督学习', cat:'basics',
    def:'用无标签数据训练，让模型自己发现数据中的规律。',
    analogy:'就像让学生自己把一堆卡片分类，没有标准答案。' },
  { en:'Data Preprocessing', zh:'数据预处理', cat:'basics',
    def:'训练前对原始数据进行清洗、格式化、归一化等操作。',
    analogy:'就像做菜前先洗菜、切菜、备料。' },
  { en:'Gradient Descent', zh:'梯度下降', cat:'basics',
    def:'通过不断调整参数来最小化误差的优化方法。',
    analogy:'就像蒙着眼睛下山，每次往最陡的方向走一步。' },
  { en:'Regression', zh:'回归', cat:'basics',
    def:'预测连续数值输出的机器学习任务。',
    analogy:'就像根据房子面积预测具体售价。' },
  { en:'Vector', zh:'向量', cat:'basics',
    def:'由一组数字组成的数学对象，用于表示数据在空间中的位置。',
    analogy:'就像地图上的坐标，能精确定位一个点。' },
  { en:'Weights', zh:'权重', cat:'basics',
    def:'神经网络中连接节点的数值，决定信号传递强度。',
    analogy:'就像道路的宽窄，越宽的路通过的车越多。' },
  { en:'Learning Rate', zh:'学习率', cat:'basics',
    def:'控制每次参数更新幅度大小的超参数。',
    analogy:'就像下山时每步迈多大，太大会跨过最低点。' },
  { en:'Backpropagation', zh:'反向传播', cat:'basics',
    def:'从输出误差反向计算每个参数应如何调整的算法。',
    analogy:'就像考完试对答案，从错误倒推哪个步骤出了问题。' },
  { en:'Clustering', zh:'聚类', cat:'basics',
    def:'将相似数据自动归为一组的无监督学习方法。',
    analogy:'就像把一堆糖果按颜色自动分堆。' },
  { en:'Probability', zh:'概率', cat:'basics',
    def:'某件事发生可能性的数值表示，范围0到1。',
    analogy:'就像天气预报说"明天下雨概率70%"。' },
  { en:'Hyperparameter', zh:'超参数', cat:'basics',
    def:'训练前人工设定、不由数据学习的配置参数。',
    analogy:'就像烤箱的温度和时间，需要人来设定。' },
  { en:'Bias', zh:'偏差', cat:'basics',
    def:'模型预测值与真实值之间的系统性误差。',
    analogy:'就像一把尺子本身刻度不准，量什么都偏。' },
  { en:'Activation Function', zh:'激活函数', cat:'basics',
    def:'决定神经元是否"激活"并传递信号的数学函数。',
    analogy:'就像开关，决定信号要不要继续往下传。' },
  { en:'Epoch', zh:'轮次', cat:'basics',
    def:'模型完整遍历一次全部训练数据称为一个轮次。',
    analogy:'就像把一本书从头到尾读了一遍。' },
  { en:'Underfitting', zh:'欠拟合', cat:'basics',
    def:'模型连训练数据都没学好，预测能力很差。',
    analogy:'就像上课没认真听，连基础题都做不对。' },
  { en:'Batch Size', zh:'批量大小', cat:'basics',
    def:'每次更新参数时使用的训练样本数量。',
    analogy:'就像每次复习多少道题再对一次答案。' },
  { en:'Variance', zh:'方差', cat:'basics',
    def:'模型对不同训练数据的敏感程度，越高越不稳定。',
    analogy:'就像情绪不稳定的人，今天好明天差。' },
  { en:'Dimensionality Reduction', zh:'降维', cat:'basics',
    def:'在保留关键信息的前提下减少数据特征数量。',
    analogy:'就像把3D立体图压缩成2D平面图，保留主要轮廓。' },

  // ── 第2类：大模型相关（按使用频率由高到低）──────────────────────
  { en:'LLM', zh:'大语言模型缩写', cat:'llm',
    def:'Large Language Model 的缩写，泛指 GPT、Claude 等大型语言模型。',
    analogy:'就像"AI助手"的专业简称。' },
  { en:'Prompt', zh:'提示词', cat:'llm',
    def:'用户输入给模型的指令或问题，引导模型生成期望输出。',
    analogy:'就像给厨师下单，描述越清楚菜做得越符合预期。' },
  { en:'Token', zh:'词元', cat:'llm',
    def:'模型处理文本的最小单位，可以是一个字、半个词或标点。',
    analogy:'就像乐高积木，文字被拆成一块块积木再处理。' },
  { en:'Hallucination', zh:'幻觉', cat:'llm',
    def:'模型生成看似合理但实际上错误或虚构的内容。',
    analogy:'就像一个人说得头头是道，但其实在胡编乱造。' },
  { en:'Context Window', zh:'上下文窗口', cat:'llm',
    def:'模型一次能"看到"并处理的最大文本长度。',
    analogy:'就像人的短期记忆，超出范围的内容就"忘了"。' },
  { en:'API', zh:'应用程序接口', cat:'llm',
    def:'让开发者通过代码调用模型能力的标准化接口。',
    analogy:'就像餐厅的点餐窗口，你下单它出餐，不用进厨房。' },
  { en:'Large Language Model', zh:'大语言模型', cat:'llm',
    def:'用海量文本训练、能理解和生成自然语言的超大规模模型。',
    analogy:'就像读过几乎所有书的超级博学者。' },
  { en:'GPT', zh:'生成式预训练模型', cat:'llm',
    def:'OpenAI 开发的自回归语言模型系列，能生成连贯文本。',
    analogy:'就像一个能接龙的高手，根据上文预测下一个词。' },
  { en:'Fine-tuning', zh:'微调', cat:'llm',
    def:'在预训练模型基础上，用特定领域数据进一步训练以专业化。',
    analogy:'就像大学选专业，在通识基础上深入某个方向。' },
  { en:'Prompt Engineering', zh:'提示词工程', cat:'llm',
    def:'通过设计和优化 prompt 来提升模型输出质量的技术和方法。',
    analogy:'就像学会如何跟聪明的助手沟通，让他更好地帮你。' },
  { en:'Temperature', zh:'温度参数', cat:'llm',
    def:'控制模型输出随机性的参数，越高越有创意，越低越保守。',
    analogy:'就像调节音乐的即兴程度，高温即兴发挥，低温按谱演奏。' },
  { en:'System Prompt', zh:'系统提示词', cat:'llm',
    def:'在对话开始前设定模型角色和行为规则的隐藏指令。',
    analogy:'就像给员工的岗前培训手册，规定他该怎么工作。' },
  { en:'Foundation Model', zh:'基础模型', cat:'llm',
    def:'在大规模数据上预训练、可适配多种下游任务的通用模型。',
    analogy:'就像万能底座，上面可以插各种不同的功能模块。' },
  { en:'Multimodal', zh:'多模态', cat:'llm',
    def:'能同时处理文字、图片、音频等多种类型数据的模型能力。',
    analogy:'就像一个人既能看图又能听声还能读文字。' },
  { en:'Chain of Thought', zh:'思维链', cat:'llm',
    def:'引导模型一步步展示推理过程再给出答案的提示技术。',
    analogy:'就像让学生"写出解题步骤"而不是直接写答案。' },
  { en:'Few-shot Learning', zh:'少样本学习', cat:'llm',
    def:'在 prompt 中提供少量示例，引导模型按示例格式回答。',
    analogy:'就像给新员工看几个范例，他就能照着做了。' },
  { en:'Knowledge Cutoff', zh:'知识截止日期', cat:'llm',
    def:'模型训练数据的最后时间点，之后的事件模型不知道。',
    analogy:'就像一本百科全书的出版日期，之后发生的事没收录。' },
  { en:'Open Source Model', zh:'开源模型', cat:'llm',
    def:'代码和权重公开、任何人都可以下载使用的模型。',
    analogy:'就像公开菜谱，任何人都能照着做这道菜。' },
  { en:'Embedding Model', zh:'嵌入模型', cat:'llm',
    def:'专门将文本转换为向量表示的模型，用于语义搜索等场景。',
    analogy:'就像把文字翻译成坐标的专用翻译官。' },
  { en:'Context Length', zh:'上下文长度', cat:'llm',
    def:'模型单次处理的最大 token 数，决定能记住多长的对话。',
    analogy:'就像一张纸能写多少字，超出就写不下了。' },
  { en:'Pre-training', zh:'预训练', cat:'llm',
    def:'在海量通用数据上训练模型，使其获得广泛的基础能力。',
    analogy:'就像读完九年义务教育，打好各科基础。' },
  { en:'Zero-shot Learning', zh:'零样本学习', cat:'llm',
    def:'不提供任何示例，直接让模型完成从未见过的任务。',
    analogy:'就像让人做从没做过的事，只靠理解能力。' },
  { en:'Latency', zh:'延迟', cat:'llm',
    def:'从发送请求到收到第一个响应之间的等待时间。',
    analogy:'就像点外卖从下单到送达的时间。' },
  { en:'Transformer', zh:'变换器架构', cat:'llm',
    def:'当前大模型的核心架构，通过注意力机制理解词语间关系。',
    analogy:'就像阅读时眼睛会在关键词之间来回扫视建立联系。' },
  { en:'Closed Source Model', zh:'闭源模型', cat:'llm',
    def:'代码和权重不公开、只能通过 API 调用的商业模型。',
    analogy:'就像餐厅的秘方，只卖成品不透露配方。' },
  { en:'In-context Learning', zh:'上下文学习', cat:'llm',
    def:'模型从当前对话的上下文中学习并调整输出，无需重新训练。',
    analogy:'就像聪明的人能从对话中快速理解你的偏好并调整。' },
  { en:'Completion', zh:'补全/生成结果', cat:'llm',
    def:'模型根据 prompt 生成的输出文本。',
    analogy:'就像厨师根据你的点单做出来的菜。' },
  { en:'Model Size', zh:'模型规模', cat:'llm',
    def:'通常用参数量（如70亿、1400亿）衡量模型的大小。',
    analogy:'就像大脑神经元的数量，越多理论上越聪明。' },
  { en:'Inference Speed', zh:'推理速度', cat:'llm',
    def:'模型生成输出的速度，通常以每秒生成的 token 数衡量。',
    analogy:'就像打字速度，每秒能打多少个字。' },
  { en:'Attention Mechanism', zh:'注意力机制', cat:'llm',
    def:'让模型在处理每个词时，自动关注句子中最相关部分的技术。',
    analogy:'就像开会时你会重点听与自己相关的内容。' },
  { en:'Quantization', zh:'量化', cat:'llm',
    def:'用更低精度数值表示模型参数，减小体积和加速推理。',
    analogy:'就像把高清图片压缩成小文件，牺牲一点质量换速度。' },
  { en:'Vision Language Model', zh:'视觉语言模型', cat:'llm',
    def:'同时理解图像和文本的模型，可以看图说话或回答图片问题。',
    analogy:'就像既会看图又会说话的全能助手。' },
  { en:'Distillation', zh:'知识蒸馏', cat:'llm',
    def:'用大模型的输出来训练小模型，让小模型学到大模型的能力。',
    analogy:'就像让大师把毕生经验浓缩传授给徒弟。' },
  { en:'Tokenization', zh:'分词/词元化', cat:'llm',
    def:'将输入文本切分成 token 序列的过程。',
    analogy:'就像把一句话拆成一个个字或词组再处理。' },
  { en:'Top-p Sampling', zh:'核采样', cat:'llm',
    def:'从概率累计达到 p 的候选词中随机选择下一个词的策略。',
    analogy:'就像从最可能的几个选项里随机挑一个，而不是总选第一名。' },
  { en:'Throughput', zh:'吞吐量', cat:'llm',
    def:'单位时间内模型能处理的请求或 token 数量。',
    analogy:'就像餐厅每小时能接待多少桌客人。' },
  { en:'Mixture of Experts', zh:'专家混合模型', cat:'llm',
    def:'由多个专门子网络组成，每次只激活部分"专家"处理输入。',
    analogy:'就像公司有各部门专家，来了问题派对应专家处理。' },
  { en:'Autoregressive', zh:'自回归', cat:'llm',
    def:'模型逐个生成 token，每个新词依赖前面所有已生成的词。',
    analogy:'就像写作文时一个字一个字往后写，后面的字参考前面的。' },
  { en:'Billion Parameters', zh:'十亿参数', cat:'llm',
    def:'模型参数量的计量单位，如7B表示70亿个参数。',
    analogy:'就像衡量书的厚度，参数越多书越厚内容越丰富。' },
  { en:'Vocabulary', zh:'词表', cat:'llm',
    def:'模型能识别和生成的所有 token 的集合。',
    analogy:'就像模型认识的所有"字"的字典。' },

  // ── 第3类：训练与调优（按使用频率由高到低）──────────────────────
  { en:'Fine-tuning', zh:'微调', cat:'training',
    def:'在预训练模型基础上，用特定领域数据进一步训练以专业化。',
    analogy:'就像大学选专业，在通识基础上深入某个方向。' },
  { en:'RLHF', zh:'基于人类反馈的强化学习', cat:'training',
    def:'用人类对模型输出的好坏评价来训练模型，使其更符合人类偏好。',
    analogy:'就像让真人评委打分，模型根据分数不断改进表演。' },
  { en:'SFT', zh:'监督微调', cat:'training',
    def:'Supervised Fine-Tuning，用高质量标注数据对预训练模型进行微调。',
    analogy:'就像用优秀范文训练写作能力。' },
  { en:'Alignment', zh:'对齐', cat:'training',
    def:'确保AI系统的目标和行为符合人类价值观和意图的研究方向。',
    analogy:'就像确保员工的工作目标和公司目标一致。' },
  { en:'Pre-training', zh:'预训练', cat:'training',
    def:'在海量通用数据上训练模型，使其获得广泛的基础能力。',
    analogy:'就像读完九年义务教育，打好各科基础。' },
  { en:'Data Cleaning', zh:'数据清洗', cat:'training',
    def:'去除训练数据中的噪声、错误、重复和低质量样本。',
    analogy:'就像淘米，把杂质和坏米挑出去。' },
  { en:'Transfer Learning', zh:'迁移学习', cat:'training',
    def:'将在一个任务上学到的知识迁移应用到另一个相关任务。',
    analogy:'就像学会骑自行车后，学摩托车会更快。' },
  { en:'LoRA', zh:'低秩适配', cat:'training',
    def:'一种高效微调方法，只训练少量新增参数，大幅降低计算成本。',
    analogy:'就像给衣服加个补丁，不用重新做整件衣服。' },
  { en:'Instruction Tuning', zh:'指令微调', cat:'training',
    def:'用"指令-回答"对数据微调模型，使其更好地遵循用户指令。',
    analogy:'就像专门训练员工"听指令做事"的岗位培训。' },
  { en:'Overfitting', zh:'过拟合', cat:'training',
    def:'模型在训练数据上表现极好，但遇到新数据就失灵。',
    analogy:'就像只会背答案，换道题就不会了。' },
  { en:'Data Augmentation', zh:'数据增强', cat:'training',
    def:'通过对原始数据做变换（翻转、裁剪等）来扩充训练集。',
    analogy:'就像把一张照片旋转、裁剪成多张，增加练习素材。' },
  { en:'GPU', zh:'图形处理器', cat:'training',
    def:'擅长并行计算的芯片，是训练深度学习模型的主要硬件。',
    analogy:'就像工厂里能同时干很多活的流水线工人。' },
  { en:'Compute', zh:'算力', cat:'training',
    def:'训练和运行AI模型所需的计算资源，通常用GPU/TPU衡量。',
    analogy:'就像工厂的机器产能，决定能生产多少、多快。' },
  { en:'Checkpoint', zh:'检查点', cat:'training',
    def:'训练过程中保存的模型状态快照，可用于恢复或评估。',
    analogy:'就像游戏存档，随时可以从这个进度继续。' },
  { en:'Synthetic Data', zh:'合成数据', cat:'training',
    def:'由程序或模型生成的人工数据，用于补充真实训练数据。',
    analogy:'就像用模拟器生成练习题，弥补真题不足。' },
  { en:'Red Teaming', zh:'红队测试', cat:'training',
    def:'专门尝试攻击和欺骗AI模型，找出安全漏洞的测试方法。',
    analogy:'就像雇黑客来测试自家系统，主动找漏洞。' },
  { en:'Safety Training', zh:'安全训练', cat:'training',
    def:'专门训练模型拒绝有害请求、避免输出危险内容的过程。',
    analogy:'就像给员工做职业道德培训，教他什么不能做。' },
  { en:'DPO', zh:'直接偏好优化', cat:'training',
    def:'不需要奖励模型、直接用人类偏好数据优化模型的方法。',
    analogy:'就像直接告诉厨师"这道菜比那道好"，省去评委环节。' },
  { en:'Reward Model', zh:'奖励模型', cat:'training',
    def:'RLHF 中用于评估模型输出质量、给出奖励分数的模型。',
    analogy:'就像评委，专门负责给选手的表现打分。' },
  { en:'Validation Set', zh:'验证集', cat:'training',
    def:'训练过程中用于调整超参数和监控模型表现的数据集。',
    analogy:'就像模拟考试，用来调整备考策略但不算最终成绩。' },
  { en:'Test Set', zh:'测试集', cat:'training',
    def:'训练完成后用于最终评估模型真实性能的独立数据集。',
    analogy:'就像高考，只在最后用一次，检验真实水平。' },
  { en:'PEFT', zh:'参数高效微调', cat:'training',
    def:'只调整模型少量参数就能适配新任务的微调技术总称。',
    analogy:'就像只改装车的某个零件，不用换整台发动机。' },
  { en:'Optimizer', zh:'优化器', cat:'training',
    def:'决定如何根据梯度更新模型参数的算法，如 Adam、SGD。',
    analogy:'就像下山时选择走路策略的向导。' },
  { en:'Early Stopping', zh:'早停', cat:'training',
    def:'当验证集性能不再提升时提前终止训练，防止过拟合。',
    analogy:'就像发现再练也没进步了，及时收手避免过度训练。' },
  { en:'Distributed Training', zh:'分布式训练', cat:'training',
    def:'将训练任务分散到多台机器或多个GPU上并行完成。',
    analogy:'就像把一个大工程分给多个工地同时施工。' },
  { en:'Data Pipeline', zh:'数据流水线', cat:'training',
    def:'从原始数据到可训练格式的自动化处理流程。',
    analogy:'就像工厂流水线，原材料进去，成品出来。' },
  { en:'Constitutional AI', zh:'宪法AI', cat:'training',
    def:'Anthropic 提出的方法，用一套原则让模型自我批评和改进。',
    analogy:'就像给AI一部"宪法"，让它自己对照检查行为是否合规。' },
  { en:'Regularization', zh:'正则化', cat:'training',
    def:'防止模型过拟合的技术，通过限制参数复杂度提升泛化能力。',
    analogy:'就像考试限制只能用基本公式，防止死记硬背。' },
  { en:'Cross Validation', zh:'交叉验证', cat:'training',
    def:'将数据分成多份轮流作为验证集，更可靠地评估模型性能。',
    analogy:'就像多次模拟考试取平均分，比一次考试更准确。' },
  { en:'Adam', zh:'Adam优化器', cat:'training',
    def:'目前最常用的优化器，自适应调整每个参数的学习率。',
    analogy:'就像聪明的向导，根据地形自动调整步伐大小。' },
  { en:'PPO', zh:'近端策略优化', cat:'training',
    def:'RLHF 中常用的强化学习算法，稳定地优化模型策略。',
    analogy:'就像稳健的训练计划，每次只进步一小步避免走偏。' },
  { en:'Class Imbalance', zh:'类别不平衡', cat:'training',
    def:'训练数据中不同类别样本数量差异悬殊的问题。',
    analogy:'就像练习题里简单题1000道、难题只有10道，模型会偏科。' },
  { en:'Convergence', zh:'收敛', cat:'training',
    def:'训练过程中损失函数趋于稳定、模型不再明显改善的状态。',
    analogy:'就像反复练习后成绩不再提升，达到了当前极限。' },
  { en:'TPU', zh:'张量处理器', cat:'training',
    def:'Google 专为机器学习设计的定制芯片，比 GPU 更高效。',
    analogy:'就像专门为某道工序定制的专用机器，比通用机器更快。' },
  { en:'Dropout', zh:'随机丢弃', cat:'training',
    def:'训练时随机关闭部分神经元，防止过拟合的正则化技术。',
    analogy:'就像训练时随机让几个队员缺席，逼其他人都能独当一面。' },
  { en:'Continual Learning', zh:'持续学习', cat:'training',
    def:'模型在学习新知识的同时不遗忘旧知识的能力和方法。',
    analogy:'就像学新技能的同时不忘记已有技能。' },
  { en:'Model Merging', zh:'模型合并', cat:'training',
    def:'将多个微调模型的权重合并成一个兼具多种能力的模型。',
    analogy:'就像把多个专家的经验融合成一个全能型人才。' },
  { en:'Batch Normalization', zh:'批归一化', cat:'training',
    def:'对每批数据的激活值做归一化，加速训练并提升稳定性。',
    analogy:'就像把不同量纲的数据统一换算成同一单位再比较。' },
  { en:'Mixed Precision Training', zh:'混合精度训练', cat:'training',
    def:'同时使用16位和32位浮点数训练，加速同时保持精度。',
    analogy:'就像粗活用大工具、精细活用小工具，提高整体效率。' },
  { en:'Catastrophic Forgetting', zh:'灾难性遗忘', cat:'training',
    def:'模型学习新任务后严重遗忘旧任务知识的现象。',
    analogy:'就像学了新语言后把母语忘了。' },
  { en:'Curriculum Learning', zh:'课程学习', cat:'training',
    def:'按从易到难的顺序安排训练数据，模拟人类学习方式。',
    analogy:'就像教材从简单到复杂编排，循序渐进。' },
  { en:'Gradient Clipping', zh:'梯度裁剪', cat:'training',
    def:'限制梯度的最大值，防止训练过程中参数更新过大导致崩溃。',
    analogy:'就像限速，防止车开太快失控。' },
  { en:'Warmup', zh:'学习率预热', cat:'training',
    def:'训练初期从小学习率逐渐增大，避免初始阶段不稳定。',
    analogy:'就像运动前先做热身，避免直接全力冲刺受伤。' },

  // ── 第4类：应用与交互（按使用频率由高到低）──────────────────────
  { en:'Chatbot', zh:'聊天机器人', cat:'application',
    def:'基于AI的对话系统，能理解用户输入并给出自然语言回复。',
    analogy:'就像一个永远在线、随时回复的客服。' },
  { en:'RAG', zh:'检索增强生成', cat:'application',
    def:'让模型先从外部知识库检索相关内容，再生成回答，减少幻觉。',
    analogy:'就像开卷考试，答题前先查资料再作答。' },
  { en:'Agent', zh:'AI智能体', cat:'application',
    def:'能自主规划、调用工具、执行多步骤任务的AI系统。',
    analogy:'就像一个能自己安排工作、调用各种工具完成任务的助理。' },
  { en:'Prompt', zh:'提示词', cat:'application',
    def:'用户输入给模型的指令或问题，引导模型生成期望输出。',
    analogy:'就像给厨师下单，描述越清楚菜做得越符合预期。' },
  { en:'Streaming', zh:'流式输出', cat:'application',
    def:'模型边生成边输出，用户无需等待全部完成即可看到结果。',
    analogy:'就像直播，边录边播，不用等录完再看。' },
  { en:'Summarization', zh:'摘要生成', cat:'application',
    def:'将长文本压缩成保留核心信息的简短摘要。',
    analogy:'就像把一本书浓缩成一页读书笔记。' },
  { en:'Translation', zh:'机器翻译', cat:'application',
    def:'AI自动将文本从一种语言转换为另一种语言。',
    analogy:'就像一个精通多国语言的即时翻译官。' },
  { en:'Code Generation', zh:'代码生成', cat:'application',
    def:'AI根据自然语言描述自动生成可运行代码的能力。',
    analogy:'就像你说"帮我做个登录页面"，AI直接写出代码。' },
  { en:'Text-to-Image', zh:'文生图', cat:'application',
    def:'根据文字描述生成对应图像的AI能力。',
    analogy:'就像你描述一幅画，AI帮你画出来。' },
  { en:'Copilot', zh:'AI副驾驶', cat:'application',
    def:'嵌入工作软件中辅助用户完成任务的AI助手形态。',
    analogy:'就像副驾驶，你开车它帮你导航、提醒、辅助操作。' },
  { en:'Tool Use', zh:'工具调用', cat:'application',
    def:'AI模型调用外部工具（搜索、计算器、代码执行等）扩展能力。',
    analogy:'就像人用手机查地图、用计算器算账，借助工具完成任务。' },
  { en:'Function Calling', zh:'函数调用', cat:'application',
    def:'模型识别用户意图后，调用预定义函数获取结构化结果。',
    analogy:'就像前台接到需求后，转接给对应部门处理。' },
  { en:'Knowledge Base', zh:'知识库', cat:'application',
    def:'存储结构化或非结构化知识供AI检索和引用的数据集合。',
    analogy:'就像公司的内部百科全书，AI可以随时查阅。' },
  { en:'Vector Database', zh:'向量数据库', cat:'application',
    def:'专门存储和检索向量数据的数据库，支持语义相似度搜索。',
    analogy:'就像按"意思相近"而不是"关键词匹配"来找文件的档案室。' },
  { en:'Semantic Search', zh:'语义搜索', cat:'application',
    def:'理解查询意图和内容语义进行搜索，而非简单关键词匹配。',
    analogy:'就像搜"天气冷穿什么"能找到羽绒服，而不只找含这几个字的页面。' },
  { en:'Multi-turn Dialogue', zh:'多轮对话', cat:'application',
    def:'AI与用户进行多次来回交流、保持上下文连贯的对话形式。',
    analogy:'就像正常聊天，能记住前面说过的话继续话题。' },
  { en:'Personalization', zh:'个性化', cat:'application',
    def:'根据用户历史行为和偏好定制AI输出的能力。',
    analogy:'就像老朋友了解你的口味，推荐你喜欢的东西。' },
  { en:'Guardrails', zh:'护栏', cat:'application',
    def:'限制AI输出范围、防止有害或偏离主题内容的约束机制。',
    analogy:'就像公路护栏，防止车辆偏离车道。' },
  { en:'Moderation', zh:'内容审核', cat:'application',
    def:'检测并过滤AI输入输出中违规、有害内容的机制。',
    analogy:'就像社区管理员，过滤不当言论。' },
  { en:'Speech-to-Text', zh:'语音转文字', cat:'application',
    def:'将语音内容自动转录为文字的AI技术。',
    analogy:'就像一个速记员，把你说的话实时记录下来。' },
  { en:'Text-to-Speech', zh:'文字转语音', cat:'application',
    def:'将文字内容转换为自然语音的AI技术。',
    analogy:'就像让AI帮你朗读文章。' },
  { en:'Human in the Loop', zh:'人机协作', cat:'application',
    def:'在AI自动化流程中保留人工审核或干预节点的设计模式。',
    analogy:'就像自动流水线上设置质检员，关键步骤人工把关。' },
  { en:'Workflow', zh:'工作流', cat:'application',
    def:'将多个AI步骤或工具串联成自动化流程的编排方式。',
    analogy:'就像工厂流水线，每个环节自动衔接完成复杂任务。' },
  { en:'Memory', zh:'记忆模块', cat:'application',
    def:'让AI在多次对话间保留用户信息和历史交互的机制。',
    analogy:'就像给AI装了一个笔记本，记住你的偏好和历史。' },
  { en:'Structured Output', zh:'结构化输出', cat:'application',
    def:'让模型按指定格式（如JSON）输出，便于程序处理。',
    analogy:'就像要求员工填表格而不是写作文，方便统计。' },
  { en:'Grounding', zh:'事实锚定', cat:'application',
    def:'将模型输出与可验证的真实数据或来源关联，减少幻觉。',
    analogy:'就像要求发言必须引用可查证的资料来源。' },
  { en:'Chunking', zh:'文本分块', cat:'application',
    def:'将长文档切分成适合模型处理的小段落的预处理步骤。',
    analogy:'就像把一本书拆成一章一章，方便分别处理。' },
  { en:'Retrieval', zh:'检索', cat:'application',
    def:'从大量文档或数据库中找到与查询最相关内容的过程。',
    analogy:'就像图书馆员根据你的需求找到最相关的书。' },
  { en:'Conversational AI', zh:'对话式AI', cat:'application',
    def:'能进行多轮自然对话、理解上下文的AI系统。',
    analogy:'就像能记住整个聊天记录、连贯交流的智能助手。' },
  { en:'Plugin', zh:'插件', cat:'application',
    def:'扩展AI能力的附加模块，让模型能访问外部服务或数据。',
    analogy:'就像手机App，给基础系统增加新功能。' },
  { en:'Citation', zh:'引用溯源', cat:'application',
    def:'AI回答时标注信息来源，让用户可以核实原始资料。',
    analogy:'就像论文的参考文献，让读者知道信息从哪来。' },
  { en:'Orchestration', zh:'编排', cat:'application',
    def:'协调多个AI模型或工具按顺序或并行执行的管理机制。',
    analogy:'就像乐队指挥，协调各乐器在正确时间演奏。' },
  { en:'Multiagent System', zh:'多智能体系统', cat:'application',
    def:'多个AI Agent 协作分工完成复杂任务的系统架构。',
    analogy:'就像一个团队，每人负责不同工作共同完成项目。' },
  { en:'MCP', zh:'模型上下文协议', cat:'application',
    def:'Anthropic 提出的标准协议，让AI模型统一接入各种外部工具。',
    analogy:'就像USB接口标准，任何设备都能用同一个接口连接。' },
  { en:'Agentic Loop', zh:'智能体循环', cat:'application',
    def:'Agent 反复执行"思考-行动-观察"直到完成任务的运行模式。',
    analogy:'就像解题时反复尝试、检验、修正直到答对。' },
  { en:'Long-term Memory', zh:'长期记忆', cat:'application',
    def:'AI跨会话持久保存用户信息和偏好的能力。',
    analogy:'就像老朋友记得你多年前说过的话。' },
  { en:'Context Management', zh:'上下文管理', cat:'application',
    def:'在有限上下文窗口内合理组织和压缩信息的策略。',
    analogy:'就像在有限的黑板上合理安排板书，重要的留着不重要的擦掉。' },
  { en:'Embedding Search', zh:'向量检索', cat:'application',
    def:'将查询转为向量后在向量数据库中找最相似内容的搜索方式。',
    analogy:'就像用"气味"找东西，而不是用名字找。' },
  { en:'API Rate Limit', zh:'API速率限制', cat:'application',
    def:'服务商对单位时间内API调用次数的上限限制。',
    analogy:'就像餐厅规定每桌每小时最多点几道菜。' },
  { en:'Webhook', zh:'网络钩子', cat:'application',
    def:'事件触发时自动向指定URL发送数据的回调机制。',
    analogy:'就像设置了一个自动通知，事情发生时自动发消息。' },
  { en:'Vibe Coding', zh:'氛围编程', cat:'application',
    def:'用自然语言描述想要的功能，让AI直接生成代码，开发者更像导演而非程序员。',
    analogy:'就像你哼出旋律，AI帮你把整首曲子编出来。' },
  { en:'No-code / Low-code', zh:'无代码/低代码', cat:'application',
    def:'通过可视化拖拽或少量配置构建应用，无需传统编程能力。',
    analogy:'就像用乐高积木搭房子，不用自己烧砖。' },
  { en:'AI-assisted Development', zh:'AI辅助开发', cat:'application',
    def:'开发者借助AI工具完成代码补全、调试、重构等编程任务的工作方式。',
    analogy:'就像有个随时待命的资深程序员坐在你旁边帮你写代码。' },
  { en:'Prompt-driven Development', zh:'提示词驱动开发', cat:'application',
    def:'以编写和优化prompt为核心工作，通过prompt控制AI完成产品功能的开发模式。',
    analogy:'就像导演用剧本指挥演员，prompt就是你的剧本。' },

  // ── 第5类：评估与能力（按使用频率由高到低）──────────────────────
  { en:'Benchmark', zh:'基准测试', cat:'evaluation',
    def:'用标准化测试集评估和比较不同模型能力的方法。',
    analogy:'就像统一考试，用同一套题衡量不同学生的水平。' },
  { en:'Hallucination', zh:'幻觉', cat:'evaluation',
    def:'模型生成看似合理但实际上错误或虚构的内容。',
    analogy:'就像一个人说得头头是道，但其实在胡编乱造。' },
  { en:'Accuracy', zh:'准确率', cat:'evaluation',
    def:'模型预测正确的样本占总样本的比例。',
    analogy:'就像考试答对题目数除以总题目数。' },
  { en:'Reasoning', zh:'推理能力', cat:'evaluation',
    def:'模型进行逻辑推导、多步骤思考和问题求解的能力。',
    analogy:'就像解数学应用题，需要一步步推导而不是直接背答案。' },
  { en:'Factuality', zh:'事实准确性', cat:'evaluation',
    def:'模型输出内容与真实世界事实相符的程度。',
    analogy:'就像新闻报道的准确性，说的是不是真的。' },
  { en:'A/B Testing', zh:'A/B测试', cat:'evaluation',
    def:'同时运行两个版本对比效果，用数据决定哪个更好。',
    analogy:'就像同时开两家店测试不同装修风格哪个更吸引顾客。' },
  { en:'Human Evaluation', zh:'人工评估', cat:'evaluation',
    def:'由人类评判者对模型输出质量进行打分或排序的评估方式。',
    analogy:'就像请真人评委而不是机器打分。' },
  { en:'Instruction Following', zh:'指令遵循', cat:'evaluation',
    def:'模型准确理解并执行用户指令的能力。',
    analogy:'就像员工能否准确理解并完成上级交代的任务。' },
  { en:'Robustness', zh:'鲁棒性', cat:'evaluation',
    def:'模型在输入有噪声、错误或对抗性扰动时保持稳定的能力。',
    analogy:'就像好的产品能经受各种恶劣环境的考验。' },
  { en:'Emergent Ability', zh:'涌现能力', cat:'evaluation',
    def:'模型规模达到某个阈值后突然出现的、小模型没有的能力。',
    analogy:'就像水加热到100度才会沸腾，量变引发质变。' },
  { en:'Leaderboard', zh:'排行榜', cat:'evaluation',
    def:'按基准测试成绩对不同模型进行排名的公开榜单。',
    analogy:'就像游戏积分榜，展示各模型的相对水平。' },
  { en:'Evals', zh:'评测集', cat:'evaluation',
    def:'用于系统性评估模型能力的测试用例集合。',
    analogy:'就像期末考试的题库，全面检验学习成果。' },
  { en:'Safety Evaluation', zh:'安全评估', cat:'evaluation',
    def:'专门测试模型是否会产生有害输出的评估体系。',
    analogy:'就像产品上市前的安全检测。' },
  { en:'Bias Detection', zh:'偏见检测', cat:'evaluation',
    def:'识别模型输出中存在的性别、种族等系统性偏见。',
    analogy:'就像检查裁判是否对某队有偏袒。' },
  { en:'F1 Score', zh:'F1分数', cat:'evaluation',
    def:'综合精确率和召回率的评估指标，平衡两者的调和平均值。',
    analogy:'就像综合考虑"不误判"和"不漏判"的综合评分。' },
  { en:'Scaling Law', zh:'规模定律', cat:'evaluation',
    def:'描述模型性能随参数量、数据量、算力增加而提升的规律。',
    analogy:'就像投入越多资源，产出越高的生产规律。' },
  { en:'MMLU', zh:'大规模多任务语言理解', cat:'evaluation',
    def:'涵盖57个学科的综合知识测试基准，衡量模型广度知识。',
    analogy:'就像高考，考察各科综合知识水平。' },
  { en:'Win Rate', zh:'胜率', cat:'evaluation',
    def:'在人类偏好评估中，某模型输出被选为更好的比例。',
    analogy:'就像擂台赛，统计赢了多少场。' },
  { en:'Coherence', zh:'连贯性', cat:'evaluation',
    def:'模型生成文本在逻辑和语义上前后一致、流畅的程度。',
    analogy:'就像一篇文章读起来是否通顺、前后不矛盾。' },
  { en:'Cost per Token', zh:'每词元成本', cat:'evaluation',
    def:'调用模型API时，处理每个token所需支付的费用。',
    analogy:'就像打印费用按页计算，token越多花费越多。' },
  { en:'Precision', zh:'精确率', cat:'evaluation',
    def:'模型预测为正例中真正是正例的比例。',
    analogy:'就像钓鱼时钓上来的鱼里有多少是你想要的鱼。' },
  { en:'Recall', zh:'召回率', cat:'evaluation',
    def:'所有真正正例中被模型正确识别出来的比例。',
    analogy:'就像所有想要的鱼里你实际钓到了多少。' },
  { en:'Perplexity', zh:'困惑度', cat:'evaluation',
    def:'衡量语言模型预测文本能力的指标，越低说明模型越好。',
    analogy:'就像考试时的不确定感，越困惑分数越低。' },
  { en:'Common Sense Reasoning', zh:'常识推理', cat:'evaluation',
    def:'模型运用日常生活常识理解和推断的能力。',
    analogy:'就像知道"下雨要带伞"这种不需要学就该懂的道理。' },
  { en:'Fluency', zh:'流畅度', cat:'evaluation',
    def:'模型生成文本在语法和表达上自然流畅的程度。',
    analogy:'就像说话是否自然，不像机器人在念稿子。' },
  { en:'Calibration', zh:'校准', cat:'evaluation',
    def:'模型输出的置信度与实际准确率相符的程度。',
    analogy:'就像天气预报说70%概率下雨，实际真的有七成概率。' },
  { en:'Needle in a Haystack', zh:'大海捞针测试', cat:'evaluation',
    def:'测试模型在超长文本中找到特定信息的能力。',
    analogy:'就像在一本厚书里找到某句特定的话。' },
  { en:'Ablation Study', zh:'消融实验', cat:'evaluation',
    def:'逐一去掉模型的某个组件，观察对性能影响的实验方法。',
    analogy:'就像逐一拆掉零件看哪个对机器最重要。' },
  { en:'Mathematical Reasoning', zh:'数学推理', cat:'evaluation',
    def:'模型理解和解决数学问题的能力。',
    analogy:'就像做数学题，需要准确计算和逻辑推导。' },
  { en:'HumanEval', zh:'代码能力评估', cat:'evaluation',
    def:'通过编程题测试模型代码生成能力的基准数据集。',
    analogy:'就像程序员面试的上机考试。' },
  { en:'Toxicity', zh:'毒性/有害性', cat:'evaluation',
    def:'模型输出包含冒犯、歧视或有害内容的程度。',
    analogy:'就像检测食品是否含有害物质。' },
  { en:'Red Line', zh:'红线', cat:'evaluation',
    def:'模型绝对不能越过的行为边界，如生成违法内容。',
    analogy:'就像法律红线，无论如何都不能触碰。' },
  { en:'Latency vs Quality', zh:'延迟与质量权衡', cat:'evaluation',
    def:'更快的响应往往意味着更低的质量，需要根据场景平衡。',
    analogy:'就像外卖速度和口味的取舍，快餐和精致料理各有场景。' },
  { en:'Context Utilization', zh:'上下文利用率', cat:'evaluation',
    def:'模型有效利用输入上下文信息的能力。',
    analogy:'就像开卷考试时能否有效利用参考资料。' },
  { en:'Long Context Performance', zh:'长上下文性能', cat:'evaluation',
    def:'模型处理超长输入时保持准确性和连贯性的能力。',
    analogy:'就像读完一整本书后还能准确回答细节问题。' },
  { en:'Capability Elicitation', zh:'能力激发', cat:'evaluation',
    def:'通过特定提示或方法挖掘模型潜在能力的技术。',
    analogy:'就像用对了方法，才能发挥出学生的真实水平。' },
  { en:'BLEU Score', zh:'BLEU分数', cat:'evaluation',
    def:'评估机器翻译质量的指标，比较生成文本与参考译文的相似度。',
    analogy:'就像对比两篇作文的相似程度来打分。' },
  { en:'Chinchilla Scaling', zh:'Chinchilla规模定律', cat:'evaluation',
    def:'DeepMind提出的规律：模型参数和训练数据应等比例增长。',
    analogy:'就像发现了最优的"肉和菜的比例"配方。' },
  { en:'Compute Optimal', zh:'算力最优', cat:'evaluation',
    def:'在给定算力预算下，最优的模型大小和数据量组合。',
    analogy:'就像在固定预算内，如何分配食材和厨师最划算。' },
  { en:'ROUGE Score', zh:'ROUGE分数', cat:'evaluation',
    def:'评估摘要生成质量的指标，衡量生成摘要与参考摘要的重叠度。',
    analogy:'就像检查你的读书笔记和标准答案有多少重合。' },
  { en:'Pass@k', zh:'k次通过率', cat:'evaluation',
    def:'代码生成中，k次尝试里至少有一次正确的概率指标。',
    analogy:'就像投篮k次至少进一个的概率。' },
  { en:'Model Card', zh:'模型卡片', cat:'evaluation',
    def:'描述模型用途、局限性、训练数据和评估结果的标准文档。',
    analogy:'就像产品说明书，告诉你这个模型能做什么、不能做什么。' },

  // ── 第6类：产品落地（按使用频率由高到低）──────────────────────
  { en:'MVP', zh:'最小可行产品', cat:'product',
    def:'用最少功能验证核心假设的早期版本，快速获取用户反馈。',
    analogy:'就像先做一辆滑板车验证"代步需求"，而不是直接造汽车。' },
  { en:'PMF', zh:'产品市场契合', cat:'product',
    def:'Product-Market Fit，产品真正满足了市场需求、用户愿意持续使用。',
    analogy:'就像钥匙和锁，完美匹配才能打开市场的门。' },
  { en:'Use Case', zh:'使用场景', cat:'product',
    def:'AI能力在特定业务场景下解决具体问题的应用方式。',
    analogy:'就像一把锤子，使用场景是"钉钉子"而不是"所有工作"。' },
  { en:'Iteration', zh:'迭代', cat:'product',
    def:'基于用户反馈快速改进产品的循环开发方式。',
    analogy:'就像不断修改草稿，每次都比上一版更好。' },
  { en:'AI Native', zh:'AI原生', cat:'product',
    def:'从设计之初就以AI为核心能力构建的产品或公司。',
    analogy:'就像"互联网原生"公司，不是把AI加进去，而是AI就是骨子里的。' },
  { en:'User Retention', zh:'用户留存', cat:'product',
    def:'用户在首次使用后持续回来使用产品的比率。',
    analogy:'就像餐厅的回头客比例，越高说明越受欢迎。' },
  { en:'DAU', zh:'日活跃用户', cat:'product',
    def:'Daily Active Users，每天使用产品的独立用户数量。',
    analogy:'就像每天进店的顾客数，衡量产品活跃程度。' },
  { en:'Feedback Loop', zh:'反馈循环', cat:'product',
    def:'收集用户对AI输出的反馈并用于持续改进模型的机制。',
    analogy:'就像餐厅收集顾客意见不断改进菜品。' },
  { en:'Onboarding', zh:'用户引导', cat:'product',
    def:'帮助新用户快速理解和上手产品的引导流程设计。',
    analogy:'就像新员工入职培训，帮他快速融入。' },
  { en:'Data Flywheel', zh:'数据飞轮', cat:'product',
    def:'用户越多→数据越多→模型越好→用户越多的正向循环。',
    analogy:'就像滚雪球，越滚越大，越大越容易滚大。' },
  { en:'Moat', zh:'护城河', cat:'product',
    def:'产品难以被竞争对手复制的核心竞争优势。',
    analogy:'就像城堡外的护城河，让敌人难以攻入。' },
  { en:'Network Effect', zh:'网络效应', cat:'product',
    def:'用户越多产品价值越大，形成自我强化的增长飞轮。',
    analogy:'就像微信，用的人越多越不能不用。' },
  { en:'Go-to-Market', zh:'市场进入策略', cat:'product',
    def:'将AI产品推向目标市场的完整计划，包括定价、渠道、推广。',
    analogy:'就像新店开业的整套方案，从选址到开业促销。' },
  { en:'User Journey', zh:'用户旅程', cat:'product',
    def:'用户从发现产品到完成目标的完整体验路径。',
    analogy:'就像顾客从进店到买单离开的全程体验地图。' },
  { en:'Engagement', zh:'用户参与度', cat:'product',
    def:'用户与产品交互的深度和频率，如使用时长、操作次数。',
    analogy:'就像顾客在店里逛了多久、买了多少东西。' },
  { en:'Cost Optimization', zh:'成本优化', cat:'product',
    def:'在保证质量前提下降低AI调用成本的策略和方法。',
    analogy:'就像在保证菜品质量的前提下降低食材成本。' },
  { en:'Pricing Model', zh:'定价模型', cat:'product',
    def:'AI产品向用户收费的方式，如按token、按月订阅、按用量。',
    analogy:'就像餐厅选择按菜点单还是自助餐模式。' },
  { en:'Compliance', zh:'合规', cat:'product',
    def:'AI产品符合法律法规、行业标准和数据隐私要求。',
    analogy:'就像食品必须通过安全认证才能上市销售。' },
  { en:'Data Privacy', zh:'数据隐私', cat:'product',
    def:'保护用户数据不被未授权访问或滥用的原则和措施。',
    analogy:'就像医生对病人信息保密的职业道德。' },
  { en:'Trust & Safety', zh:'信任与安全', cat:'product',
    def:'确保AI产品不被滥用、保护用户安全的策略和机制。',
    analogy:'就像平台的安全部门，维护健康的使用环境。' },
  { en:'LLMOps', zh:'大模型运维', cat:'product',
    def:'管理大模型从开发、部署到监控的全生命周期运营体系。',
    analogy:'就像DevOps，但专门针对AI模型的运维管理。' },
  { en:'Observability', zh:'可观测性', cat:'product',
    def:'通过日志、指标、追踪全面了解AI系统运行状态的能力。',
    analogy:'就像汽车仪表盘，实时显示各项运行指标。' },
  { en:'A/B Deployment', zh:'灰度发布', cat:'product',
    def:'先向小部分用户推送新版本，验证稳定后再全量发布。',
    analogy:'就像新菜先给少数顾客试吃，好评后再上菜单。' },
  { en:'Vertical AI', zh:'垂直AI', cat:'product',
    def:'专注于特定行业或场景的AI产品，如医疗AI、法律AI。',
    analogy:'就像专科医院，专注某个领域做到极致。' },
  { en:'AI Product Manager', zh:'AI产品经理', cat:'product',
    def:'负责定义AI产品方向、协调技术与业务、推动落地的角色。',
    analogy:'就像建筑师，既懂技术可行性又懂用户需求。' },
  { en:'Responsible AI', zh:'负责任的AI', cat:'product',
    def:'以公平、透明、安全、可问责为原则开发和部署AI的理念。',
    analogy:'就像医疗伦理，技术再强也要以人为本。' },
  { en:'Explainability', zh:'可解释性', cat:'product',
    def:'AI做出某个决策或输出时，能向用户说明原因的能力。',
    analogy:'就像法官判决必须说明理由，不能只给结论。' },
  { en:'Switching Cost', zh:'切换成本', cat:'product',
    def:'用户从当前AI产品迁移到竞品所需付出的时间、金钱和精力。',
    analogy:'就像换手机要迁移所有数据和重新学习的麻烦程度。' },
  { en:'Enterprise Sales', zh:'企业销售', cat:'product',
    def:'向大型企业客户销售AI产品的销售模式，周期长、金额大。',
    analogy:'就像给大公司做定制装修，谈判周期长但合同金额大。' },
  { en:'Platform Play', zh:'平台策略', cat:'product',
    def:'构建生态系统让第三方在上面开发应用的商业模式。',
    analogy:'就像App Store，自己做平台让别人来开发应用。' },
  { en:'API-first', zh:'API优先', cat:'product',
    def:'以API为核心产品形态，让开发者集成到自己产品中的策略。',
    analogy:'就像卖食材给餐厅，而不是直接开餐厅。' },
  { en:'Horizontal AI', zh:'水平AI', cat:'product',
    def:'跨行业通用的AI能力平台，如通用对话、通用搜索。',
    analogy:'就像综合医院，什么科都有。' },
  { en:'Caching', zh:'缓存', cat:'product',
    def:'存储常见请求的结果，相同请求直接返回缓存避免重复调用。',
    analogy:'就像把常点的外卖提前备好，下单立刻出餐。' },
  { en:'Fallback', zh:'降级策略', cat:'product',
    def:'主模型不可用时自动切换到备用方案保证服务连续性。',
    analogy:'就像停电时自动启动备用发电机。' },
  { en:'AI Governance', zh:'AI治理', cat:'product',
    def:'组织内部管理AI使用、风险和合规的政策和流程体系。',
    analogy:'就像公司的合规部门，确保AI使用符合规范。' },
  { en:'Prompt Management', zh:'提示词管理', cat:'product',
    def:'对产品中使用的prompt进行版本控制、测试和优化的系统。',
    analogy:'就像代码版本管理，但管的是prompt。' },
  { en:'Shadow Mode', zh:'影子模式', cat:'product',
    def:'AI系统在后台运行但不影响实际决策，用于验证效果的测试方式。',
    analogy:'就像新员工先旁观不操作，观察一段时间再上手。' },
  { en:'AI Gateway', zh:'AI网关', cat:'product',
    def:'统一管理多个AI模型调用、处理路由和限流的中间层。',
    analogy:'就像公司的前台，统一接待和分配所有来访请求。' },
  { en:'Latency SLA', zh:'延迟服务协议', cat:'product',
    def:'对用户承诺的响应时间上限，是产品质量的重要指标。',
    analogy:'就像外卖平台承诺"30分钟送达"的服务保证。' },
  { en:'Human Baseline', zh:'人类基准', cat:'product',
    def:'用人类专家的表现作为衡量AI能力的参照标准。',
    analogy:'就像用世界冠军的成绩作为AI运动员的目标。' },
  { en:'PRD', zh:'产品需求文档', cat:'product',
    def:'Product Requirements Document，描述产品功能、逻辑和验收标准的核心文档。',
    analogy:'就像建筑图纸，施工前把每个细节都写清楚。' },
  { en:'User Story', zh:'用户故事', cat:'product',
    def:'以"作为…我想要…以便…"格式描述用户需求的敏捷开发方法。',
    analogy:'就像从用户视角写的一句需求小纸条。' },
  { en:'Roadmap', zh:'产品路线图', cat:'product',
    def:'按时间轴规划产品功能迭代方向和优先级的战略文档。',
    analogy:'就像旅行计划表，标明什么时候去哪里、做什么。' },
  { en:'Prioritization', zh:'优先级排序', cat:'product',
    def:'在资源有限时决定哪些需求先做、哪些后做的决策过程。',
    analogy:'就像急诊室分诊，先救最紧急的病人。' },
  { en:'OKR', zh:'目标与关键结果', cat:'product',
    def:'Objectives and Key Results，设定目标并用可量化指标衡量完成度的管理框架。',
    analogy:'就像定下"期末考前三名"的目标，再拆解成每周学习计划。' },
  { en:'KPI', zh:'关键绩效指标', cat:'product',
    def:'衡量产品或团队目标完成情况的量化指标。',
    analogy:'就像体检报告里的各项数值，一眼看出健康状况。' },
  { en:'User Research', zh:'用户研究', cat:'product',
    def:'通过访谈、问卷、观察等方法深入了解用户需求和行为的过程。',
    analogy:'就像医生问诊，先搞清楚病人哪里不舒服再开药。' },
  { en:'Pain Point', zh:'痛点', cat:'product',
    def:'用户在完成某个目标时遇到的核心障碍或不满。',
    analogy:'就像鞋子里的一粒沙，小但让人难以忍受。' },
  { en:'Stakeholder', zh:'利益相关方', cat:'product',
    def:'对产品决策有影响或被产品影响的所有人，如用户、老板、合作方。',
    analogy:'就像一台戏的所有相关人：演员、导演、投资人、观众。' },
  { en:'Sprint', zh:'冲刺周期', cat:'product',
    def:'敏捷开发中固定时长（通常1-2周）的迭代开发周期。',
    analogy:'就像短跑比赛，在规定时间内全力完成一批任务。' },
];

